(function(){var h={},mt={},c={id:"424324e8a0bc2c831af01cfd9e1d0a95",dm:["csp.escience.cn"],js:"tongji.baidu.com/hm-web/js/",etrk:[],icon:'/hmt/icon/21|gif|20|20',ctrk:false,align:-1,nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:1,vcard:5125963,qiao:0,lxb:0,kbtrk:0,pt:0,aet:'',hca:'B33966F448385D35',conv:0,med:0,cvcc:'',cvcf:[],apps:''};var r=void 0,s=!0,t=null,u=!1;mt.cookie={};mt.cookie.set=function(b,a,d){var f;d.W&&(f=new Date,f.setTime(f.getTime()+d.W));document.cookie=b+"="+a+(d.domain?"; domain="+d.domain:"")+(d.path?"; path="+d.path:"")+(f?"; expires="+f.toGMTString():"")+(d.Jb?"; secure":"")};mt.cookie.get=function(b){return(b=RegExp("(^| )"+b+"=([^;]*)(;|$)").exec(document.cookie))?b[2]:t};mt.lang={};mt.lang.d=function(b,a){return"[object "+a+"]"==={}.toString.call(b)};
mt.lang.va=function(b){return mt.lang.d(b,"Number")&&isFinite(b)};mt.lang.ba=function(){return mt.lang.d(c.aet,"String")};mt.lang.j=function(b){return b.replace?b.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):b};mt.lang.trim=function(b){return b.replace(/^\s+|\s+$/g,"")};mt.lang.C=function(b,a){var d=u;if(b==t||!mt.lang.d(b,"Array")||a===r)return d;if(Array.prototype.indexOf)d=-1!==b.indexOf(a);else for(var f=0;f<b.length;f++)if(b[f]===a){d=s;break}return d};
(function(){var b=mt.lang;mt.e={};mt.e.qa=function(a){return document.getElementById(a)};mt.e.$=function(a,d){var b=[],g=[];if(!a)return g;for(;a.parentNode!=t;){for(var l=0,p=0,m=a.parentNode.childNodes.length,e=0;e<m;e++){var k=a.parentNode.childNodes[e];if(k.nodeName===a.nodeName&&(l++,k===a&&(p=l),0<p&&1<l))break}if((m=""!==a.id)&&d){b.unshift("#"+encodeURIComponent(a.id));break}else m&&(m="#"+encodeURIComponent(a.id),m=0<b.length?m+">"+b.join(">"):m,g.push(m)),b.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+
(1<l?"["+p+"]":""));a=a.parentNode}g.push(b.join(">"));return g};mt.e.Va=function(a){return(a=mt.e.$(a,s))&&a.length?String(a[0]):""};mt.e.Fb=function(a){return mt.e.$(a,u)};mt.e.Db=function(a,b){for(b=b.toUpperCase();(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==b)return a;return t};mt.e.Qa=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};mt.e.Eb=function(a){var b={top:0,left:0};if(!a)return b;var f=mt.e.Qa(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(b=a.getBoundingClientRect());
return{top:b.top+(window.pageYOffset||f.scrollTop)-(f.clientTop||0),left:b.left+(window.pageXOffset||f.scrollLeft)-(f.clientLeft||0)}};mt.e.getAttribute=function(a,b){var f=a.getAttribute&&a.getAttribute(b)||t;if(!f&&a.attributes&&a.attributes.length)for(var g=a.attributes,l=g.length,p=0;p<l;p++)g[p].nodeName===b&&(f=g[p].nodeValue);return f};mt.e.K=function(a){var b="document";a.tagName!==r&&(b=a.tagName);return b.toLowerCase()};mt.e.Xa=function(a){var d="";a.textContent?d=b.trim(a.textContent):
a.innerText&&(d=b.trim(a.innerText));d&&(d=d.replace(/\s+/g," ").substring(0,255));return d};mt.e.Ra=function(a){var b=mt.e.K(a);"input"===b&&("button"===a.type||"submit"===a.type)?a=a.value||"":"img"===b?(b=mt.e.getAttribute,a=b(a,"alt")||b(a,"title")||b(a,"src")):a="body"===b||"html"===b?["(hm-default-content-for-",b,")"].join(""):mt.e.Xa(a);return String(a).substring(0,255)};(function(){(mt.e.za=function(){function a(){if(!a.N){a.N=s;for(var b=0,d=g.length;b<d;b++)g[b]()}}function b(){try{document.documentElement.doScroll("left")}catch(f){setTimeout(b,
1);return}a()}var f=u,g=[],l;document.addEventListener?l=function(){document.removeEventListener("DOMContentLoaded",l,u);a()}:document.attachEvent&&(l=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",l),a())});(function(){if(!f)if(f=s,"complete"===document.readyState)a.N=s;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",l,u),window.addEventListener("load",a,u);else if(document.attachEvent){document.attachEvent("onreadystatechange",
l);window.attachEvent("onload",a);var g=u;try{g=window.frameElement==t}catch(m){}document.documentElement.doScroll&&g&&b()}})();return function(b){a.N?b():g.push(b)}}()).N=u})();return mt.e})();mt.event={};mt.event.c=function(b,a,d){b.attachEvent?b.attachEvent("on"+a,function(a){d.call(b,a)}):b.addEventListener&&b.addEventListener(a,d,u)};mt.event.preventDefault=function(b){b.preventDefault?b.preventDefault():b.returnValue=u};
(function(){var b=mt.event;mt.g={};mt.g.ua=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.g.gb=/msie (\d+\.\d+)/i.test(navigator.userAgent)?document.documentMode||+RegExp.$1:r;mt.g.cookieEnabled=navigator.cookieEnabled;mt.g.javaEnabled=navigator.javaEnabled();mt.g.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.g.lb=(window.screen.width||0)+"x"+(window.screen.height||0);mt.g.colorDepth=window.screen.colorDepth||0;mt.g.L=function(){var a;
a=a||document;return parseInt(window.pageYOffset||a.documentElement.scrollTop||a.body&&a.body.scrollTop||0,10)};mt.g.B=function(){var a=document;return parseInt(window.innerHeight||a.documentElement.clientHeight||a.body&&a.body.clientHeight||0,10)};mt.g.orientation=0;(function(){function a(){var a=0;window.orientation!==r&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==r)&&(a=screen.orientation.angle);mt.g.orientation=a}a();b.c(window,"orientationchange",a)})();return mt.g})();
mt.o={};mt.o.parse=function(){return(new Function('return (" + source + ")'))()};
mt.o.stringify=function(){function b(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var b=d[a];if(b)return b;b=a.charCodeAt();return"\\u00"+Math.floor(b/16).toString(16)+(b%16).toString(16)}));return'"'+a+'"'}function a(a){return 10>a?"0"+a:a}var d={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(d){switch(typeof d){case "undefined":return"undefined";case "number":return isFinite(d)?String(d):"null";case "string":return b(d);case "boolean":return String(d);
default:if(d===t)return"null";if(d instanceof Array){var g=["["],l=d.length,p,m,e;for(m=0;m<l;m++)switch(e=d[m],typeof e){case "undefined":case "function":case "unknown":break;default:p&&g.push(","),g.push(mt.o.stringify(e)),p=1}g.push("]");return g.join("")}if(d instanceof Date)return'"'+d.getFullYear()+"-"+a(d.getMonth()+1)+"-"+a(d.getDate())+"T"+a(d.getHours())+":"+a(d.getMinutes())+":"+a(d.getSeconds())+'"';p=["{"];m=mt.o.stringify;for(l in d)if(Object.prototype.hasOwnProperty.call(d,l))switch(e=
d[l],typeof e){case "undefined":case "unknown":case "function":break;default:g&&p.push(","),g=1,p.push(m(l)+":"+m(e))}p.push("}");return p.join("")}}}();mt.localStorage={};mt.localStorage.Q=function(){if(!mt.localStorage.h)try{mt.localStorage.h=document.createElement("input"),mt.localStorage.h.type="hidden",mt.localStorage.h.style.display="none",mt.localStorage.h.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.h)}catch(b){return u}return s};
mt.localStorage.set=function(b,a,d){var f=new Date;f.setTime(f.getTime()+d||31536E6);try{window.localStorage?(a=f.getTime()+"|"+a,window.localStorage.setItem(b,a)):mt.localStorage.Q()&&(mt.localStorage.h.expires=f.toUTCString(),mt.localStorage.h.load(document.location.hostname),mt.localStorage.h.setAttribute(b,a),mt.localStorage.h.save(document.location.hostname))}catch(g){}};
mt.localStorage.get=function(b){if(window.localStorage){if(b=window.localStorage.getItem(b)){var a=b.indexOf("|"),d=b.substring(0,a)-0;if(d&&d>(new Date).getTime())return b.substring(a+1)}}else if(mt.localStorage.Q())try{return mt.localStorage.h.load(document.location.hostname),mt.localStorage.h.getAttribute(b)}catch(f){}return t};
mt.localStorage.remove=function(b){if(window.localStorage)window.localStorage.removeItem(b);else if(mt.localStorage.Q())try{mt.localStorage.h.load(document.location.hostname),mt.localStorage.h.removeAttribute(b),mt.localStorage.h.save(document.location.hostname)}catch(a){}};mt.sessionStorage={};mt.sessionStorage.set=function(b,a){if(window.sessionStorage)try{window.sessionStorage.setItem(b,a)}catch(d){}};
mt.sessionStorage.get=function(b){return window.sessionStorage?window.sessionStorage.getItem(b):t};mt.sessionStorage.remove=function(b){window.sessionStorage&&window.sessionStorage.removeItem(b)};mt.Aa={};mt.Aa.log=function(b,a){var d=new Image,f="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[f]=d;d.onload=d.onerror=d.onabort=function(){d.onload=d.onerror=d.onabort=t;d=window[f]=t;a&&a(b)};d.src=b};mt.ha={};
mt.ha.Ya=function(){var b="";if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];a&&a.description&&(b=a.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(b=a.GetVariable("$version"))&&(b=b.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(d){}return b};
mt.ha.Cb=function(b,a,d,f,g){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+b+'" width="'+d+'" height="'+f+'"><param name="movie" value="'+a+'" /><param name="flashvars" value="'+(g||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+b+'" width="'+d+'" height="'+f+'" src="'+a+'" flashvars="'+(g||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.k=function(b,a){var d=b.match(RegExp("(^|&|\\?|#)("+a+")=([^&#]*)(&|$|#)",""));return d?d[3]:t};mt.url.Gb=function(b){return(b=b.match(/^(https?:)\/\//))?b[1]:t};mt.url.Ta=function(b){return(b=b.match(/^(https?:\/\/)?([^\/\?#]*)/))?b[2].replace(/.*@/,""):t};mt.url.Z=function(b){return(b=mt.url.Ta(b))?b.replace(/:\d+$/,""):b};mt.url.$=function(b){return(b=b.match(/^(https?:\/\/)?[^\/]*(.*)/))?b[2].replace(/[\?#].*/,"").replace(/^$/,"/"):t};
(function(){function b(){for(var a=u,b=document.getElementsByTagName("script"),f=b.length,f=100<f?100:f,g=0;g<f;g++){var l=b[g].src;if(l&&0===l.indexOf("https://hm.baidu.com/h")){a=s;break}}return a}return h.Pa=b})();var A=h.Pa;
h.l={fb:"http://tongji.baidu.com/hm-web/welcome/ico",ya:"hm.baidu.com/hm.gif",Fa:"tongji.baidu.com",bb:"hmmd",cb:"hmpl",wb:"utm_medium",ab:"hmkw",yb:"utm_term",Za:"hmci",vb:"utm_content",eb:"hmsr",xb:"utm_source",$a:"hmcu",ub:"utm_campaign",z:0,p:Math.round(+new Date/1E3),A:Math.round(+new Date/1E3)%65535,protocol:"https:"===document.location.protocol?"https:":"http:",da:A()||"https:"===document.location.protocol?"https:":"http:",Hb:0,Ab:6E5,ib:6E5,Ib:5E3,Bb:5,U:1024,zb:1,G:2147483647,Ba:"hca kb cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn ct u tt hh".split(" "),
D:s,na:["a","input","button"],Ha:{id:"data-hm-id",T:"data-hm-class",ka:"data-hm-xpath",content:"data-hm-content",P:"data-hm-tag",link:"data-hm-link"},ma:"data-hm-enabled",la:"data-hm-disabled"};(function(){var b={s:{},c:function(a,b){this.s[a]=this.s[a]||[];this.s[a].push(b)},J:function(a,b){this.s[a]=this.s[a]||[];for(var f=this.s[a].length,g=0;g<f;g++)this.s[a][g](b)}};return h.m=b})();
(function(){function b(b,f){var g=document.createElement("script");g.charset="utf-8";a.d(f,"Function")&&(g.readyState?g.onreadystatechange=function(){if("loaded"===g.readyState||"complete"===g.readyState)g.onreadystatechange=t,f()}:g.onload=function(){f()});g.src=b;var l=document.getElementsByTagName("script")[0];l.parentNode.insertBefore(g,l)}var a=mt.lang;return h.load=b})();
(function(){function b(){var b="";h.b.a.nv?(b=encodeURIComponent(document.referrer),window.sessionStorage?d.set("Hm_from_"+c.id,b):a.set("Hm_from_"+c.id,b,864E5)):b=(window.sessionStorage?d.get("Hm_from_"+c.id):a.get("Hm_from_"+c.id))||"";return b}var a=mt.localStorage,d=mt.sessionStorage;return h.pa=b})();
(function(){var b=h.l,a={init:function(){if(""!==c.icon){var a=c.icon.split("|"),f=b.fb+"?s="+c.id,g="https://hmcdn.baidu.com/static"+a[0]+".gif";document.write("swf"===a[1]||"gif"===a[1]?'<a href="'+f+'" target="_blank"><img border="0" src="'+g+'" width="'+a[2]+'" height="'+a[3]+'"></a>':'<a href="'+f+'" target="_blank">'+a[0]+"</a>")}}};h.m.c("pv-b",a.init);return a})();
(function(){var b=mt.lang,a=mt.e,d=mt.event,f=mt.g,g=h.l,l=h.m,p=+new Date,m=[],e={oa:function(){return function(k){if(h.b&&h.b.D&&c.aet&&c.aet.length){var d=k.target||k.srcElement;if(d){var n=h.b.na,q=a.getAttribute(d,g.ma)!=t?s:u;if(a.getAttribute(d,g.la)==t)if(q)e.R(e.Y(d,k));else{var f=a.K(d);if(b.C(n,"*")||b.C(n,f))e.R(e.Y(d,k));else for(;d.parentNode!=t;){var q=d.parentNode,f=a.K(q),v="a"===f&&b.C(n,"a")?s:u,f="button"===f&&b.C(n,"button")?s:u,y=a.getAttribute(q,g.ma)!=t?s:u;if(a.getAttribute(q,
g.la)==t&&(v||f||y)){e.R(e.Y(q,k));break}d=d.parentNode}}}}}},Y:function(k,d){var n={},q=g.Ha;n.id=a.getAttribute(k,q.id)||a.getAttribute(k,"id")||"";n.T=a.getAttribute(k,q.T)||a.getAttribute(k,"class")||"";n.ka=a.getAttribute(k,q.ka)||a.Va(k);n.content=a.getAttribute(k,q.content)||a.Ra(k);n.P=a.getAttribute(k,q.P)||a.K(k);n.link=a.getAttribute(k,q.link)||a.getAttribute(k,"href")||"";n.type=d.type||"click";q=b.va(k.offsetTop)?k.offsetTop:0;"click"===d.type?q=f.ua?d.clientY+Math.max(document.documentElement.scrollTop,
document.body.scrollTop):d.pageY:"touchend"===d.type&&(d.ea&&b.d(d.ea.changedTouches,"Array")&&d.ea.changedTouches.length)&&(q=d.ea.changedTouches[0].pageY);n.tb=q;return n},R:function(a){var d=b.j,d=[+new Date-(h.b.w!==r?h.b.w:p),d(a.id),d(a.T),d(a.P),d(a.ka),d(a.link),d(a.content),a.type,a.tb].join("*");e.S(d);b.C(["a"],a.P)&&b.d(this.H(),"Function")&&this.H()()},S:function(a){a.length>g.U||(encodeURIComponent(m.join("!")+a).length>g.U&&(e.I(m.join("!")),m=[]),m.push(a))},I:function(a){h.b.a.et=
5;h.b.a.ep=a;h.b.i()},H:function(){return function(){m&&m.length&&(e.I(m.join("!")),m=[])}}};b.ba()&&""!==c.aet&&l.c("pv-b",function(){d.c(document,"click",e.oa());"ontouchend"in document&&d.c(window,"touchend",e.oa());d.c(window,"unload",e.H())});return e})();
(function(){var b=mt.event,a=mt.g,d=h.l,f=h.m,g=+new Date,l=[],p=t,m={La:function(){return function(){h.b&&(h.b.D&&c.aet&&c.aet.length)&&(window.clearTimeout(p),p=window.setTimeout(function(){m.Da(a.L()+a.B())},150))}},Da:function(a){m.S([+new Date-(h.b.w!==r?h.b.w:g),a].join("*"))},S:function(a){if(encodeURIComponent(l.join("!")+a).length>d.U||5<l.length)m.I(l.join("!")),l=[];l.push(a)},I:function(b){h.b.a.et=6;h.b.a.vh=a.B();h.b.a.ep=b;h.b.i()},H:function(){return function(){l&&l.length&&(m.I(l.join("!")),
l=[])}}};mt.lang.ba()&&""!==c.aet&&f.c("pv-b",function(){b.c(window,"scroll",m.La());b.c(window,"unload",m.H())});return m})();
(function(){var b=mt.e,a=h.l,d=h.load,f=h.pa;h.m.c("pv-b",function(){var g=a.protocol+"//crs.baidu.com/";c.rec&&b.za(function(){for(var l=0,p=c.rp.length;l<p;l++){var m=c.rp[l][0],e=c.rp[l][1],k=b.qa("hm_t_"+m);if(e&&!(2==e&&!k||k&&""!==k.innerHTML))k="",k=Math.round(Math.random()*a.G),k=4==e?g+"hl.js?"+["siteId="+c.id,"planId="+m,"rnd="+k].join("&"):g+"t.js?"+["siteId="+c.id,"planId="+m,"from="+f(),"referer="+encodeURIComponent(document.referrer),"title="+encodeURIComponent(document.title),"rnd="+
k].join("&"),d(k)}})})})();(function(){var b=h.l,a=h.load,d=h.pa;h.m.c("pv-b",function(){if(c.trust&&c.vcard){var f="https://tag.baidu.com/vcard/v.js?"+["siteid="+c.vcard,"url="+encodeURIComponent(document.location.href),"source="+d(),"rnd="+Math.round(Math.random()*b.G),"hm=1"].join("&");a(f)}})})();
(function(){function b(){return function(){h.b.a.nv=0;h.b.a.st=4;h.b.a.et=3;h.b.a.ep=h.V.Ua()+","+h.V.Sa();h.b.i()}}function a(){clearTimeout(z);var b;v&&(b="visible"==document[v]);y&&(b=!document[y]);m="undefined"==typeof b?s:b;if((!p||!e)&&m&&k)x=s,n=+new Date;else if(p&&e&&(!m||!k))x=u,q+=+new Date-n;p=m;e=k;z=setTimeout(a,100)}function d(a){var k=document,b="";if(a in k)b=a;else for(var n=["webkit","ms","moz","o"],d=0;d<n.length;d++){var q=n[d]+a.charAt(0).toUpperCase()+a.slice(1);if(q in k){b=
q;break}}return b}function f(b){if(!("focus"==b.type||"blur"==b.type)||!(b.target&&b.target!=window))k="focus"==b.type||"focusin"==b.type?s:u,a()}var g=mt.event,l=h.m,p=s,m=s,e=s,k=s,w=+new Date,n=w,q=0,x=s,v=d("visibilityState"),y=d("hidden"),z;a();(function(){var b=v.replace(/[vV]isibilityState/,"visibilitychange");g.c(document,b,a);g.c(window,"pageshow",a);g.c(window,"pagehide",a);"object"==typeof document.onfocusin?(g.c(document,"focusin",f),g.c(document,"focusout",f)):(g.c(window,"focus",f),
g.c(window,"blur",f))})();h.V={Ua:function(){return+new Date-w},Sa:function(){return x?+new Date-n+q:q}};l.c("pv-b",function(){g.c(window,"unload",b())});return h.V})();
(function(){var b=mt.lang,a=h.l,d=h.load,f={hb:function(g){if((window._dxt===r||b.d(window._dxt,"Array"))&&"undefined"!==typeof h.b){var f=h.b.X();d([a.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(f)].join(""),g)}},rb:function(a){if(b.d(a,"String")||b.d(a,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",a])}};return h.Ja=f})();
(function(){function b(a,b,n,d){if(!(a===r||b===r||d===r)){if(""===a)return[b,n,d].join("*");a=String(a).split("!");for(var e,f=u,g=0;g<a.length;g++)if(e=a[g].split("*"),String(b)===e[0]){e[1]=n;e[2]=d;a[g]=e.join("*");f=s;break}f||a.push([b,n,d].join("*"));return a.join("!")}}function a(b){for(var e in b)if({}.hasOwnProperty.call(b,e)){var n=b[e];d.d(n,"Object")||d.d(n,"Array")?a(n):b[e]=String(n)}}var d=mt.lang,f=mt.o,g=mt.g,l=h.l,p=h.m,m=h.Ja,e={F:[],O:0,wa:u,r:{ia:"",page:""},init:function(){e.f=
0;p.c("pv-b",function(){e.Ka();e.Na()});p.c("pv-d",function(){e.Oa();e.r.page=""});p.c("stag-b",function(){h.b.a.api=e.f||e.O?e.f+"_"+e.O:"";h.b.a.ct=[decodeURIComponent(h.b.getData("Hm_ct_"+c.id)||""),e.r.ia,e.r.page].join("!")});p.c("stag-d",function(){h.b.a.api=0;e.f=0;e.O=0})},Ka:function(){var a=window._hmt||[];if(!a||d.d(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,b=0;b<arguments.length;b++){var k=arguments[b];d.d(k,"Array")&&(a.cmd[a.id].push(k),"_setAccount"===
k[0]&&(1<k.length&&/^[0-9a-f]{32}$/.test(k[1]))&&(k=k[1],a.id=k,a.cmd[k]=a.cmd[k]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},Na:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],d=/^_track(Event|MobConv|Order|RTEvent)$/,q=0,f=b.length;q<f;q++){var g=b[q];d.test(g[0])?e.F.push(g):e.fa(g)}a.cmd[c.id]={push:e.fa}},Oa:function(){if(0<e.F.length)for(var a=0,b=e.F.length;a<b;a++)e.fa(e.F[a]);e.F=t},fa:function(a){var b=a[0];if(e.hasOwnProperty(b)&&
d.d(e[b],"Function"))e[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(e.f|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],u===a||s===a))e.f|=2,h.b.sa=a},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"===a[1].charAt(0)){e.f|=4;h.b.a.et=0;h.b.a.ep="";h.b.a.vl=g.L()+g.B();h.b.a.kb=0;h.b.aa?(h.b.a.nv=0,h.b.a.st=4):h.b.aa=s;var b=h.b.a.u,d=h.b.a.su;h.b.a.u=l.protocol+"//"+document.location.host+a[1];e.wa||(h.b.a.su=document.location.href);h.b.i();h.b.a.u=b;
h.b.a.su=d;h.b.w=+new Date}},_trackEvent:function(a){2<a.length&&(e.f|=8,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=4,h.b.a.ep=d.j(a[1])+"*"+d.j(a[2])+(a[3]?"*"+d.j(a[3]):"")+(a[4]?"*"+d.j(a[4]):""),h.b.i())},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],n=a[4]||3;if(0<b&&6>b&&0<n&&4>n){e.O++;for(var q=(h.b.a.cv||"*").split("!"),f=q.length;f<b-1;f++)q.push("*");q[b-1]=n+"*"+d.j(a[2])+"*"+d.j(a[3]);h.b.a.cv=q.join("!");a=h.b.a.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?h.b.setData("Hm_cv_"+
c.id,encodeURIComponent(a),c.age):h.b.jb("Hm_cv_"+c.id)}}},_setUserTag:function(a){if(!(3>a.length)){var e=d.j(a[1]);a=d.j(a[2]);if(e!==r&&a!==r){var n=decodeURIComponent(h.b.getData("Hm_ct_"+c.id)||""),n=b(n,e,1,a);h.b.setData("Hm_ct_"+c.id,encodeURIComponent(n),c.age)}}},_setVisitTag:function(a){if(!(3>a.length)){var f=d.j(a[1]);a=d.j(a[2]);if(f!==r&&a!==r){var n=e.r.ia,n=b(n,f,2,a);e.r.ia=n}}},_setPageTag:function(a){if(!(3>a.length)){var f=d.j(a[1]);a=d.j(a[2]);if(f!==r&&a!==r){var n=e.r.page,
n=b(n,f,3,a);e.r.page=n}}},_setReferrerOverride:function(a){1<a.length&&(h.b.a.su=a[1].charAt&&"/"===a[1].charAt(0)?l.protocol+"//"+window.location.host+a[1]:a[1],e.wa=s)},_trackOrder:function(b){b=b[1];d.d(b,"Object")&&(a(b),e.f|=16,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=94,h.b.a.ep=f.stringify(b),h.b.i())},_trackMobConv:function(a){if(a={webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])e.f|=32,h.b.a.et=93,h.b.a.ep=a,h.b.i()},_trackRTPageview:function(b){b=b[1];d.d(b,"Object")&&(a(b),b=f.stringify(b),
512>=encodeURIComponent(b).length&&(e.f|=64,h.b.a.rt=b))},_trackRTEvent:function(b){b=b[1];if(d.d(b,"Object")){a(b);b=encodeURIComponent(f.stringify(b));var g=function(a){var b=h.b.a.rt;e.f|=128;h.b.a.et=90;h.b.a.rt=a;h.b.i();h.b.a.rt=b},n=b.length;if(900>=n)g.call(this,b);else for(var n=Math.ceil(n/900),q="block|"+Math.round(Math.random()*l.G).toString(16)+"|"+n+"|",m=[],v=0;v<n;v++)m.push(v),m.push(b.substring(900*v,900*v+900)),g.call(this,q+m.join("|")),m=[]}},_setUserId:function(a){a=a[1];m.hb();
m.rb(a)},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],u===a||s===a))h.b.ta=a},_setAutoEventTracking:function(a){if(1<a.length&&(a=a[1],u===a||s===a))h.b.D=a}};e.init();h.Ga=e;return h.Ga})();
(function(){function b(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=s,this.a={},this.ta=this.sa=s,this.D=k.D,this.na=g.ba()&&0<c.aet.length?c.aet.split(","):"",this.aa=u,this.init())}var a=mt.url,d=mt.Aa,f=mt.ha,g=mt.lang,l=mt.cookie,p=mt.g,m=mt.localStorage,e=mt.sessionStorage,k=h.l,w=h.m;b.prototype={ca:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},xa:function(a,b){a=a.replace(/^https?:\/\//,
"");return 0===a.indexOf(b)},M:function(b){for(var d=0;d<c.dm.length;d++)if(-1<c.dm[d].indexOf("/")){if(this.xa(b,c.dm[d]))return s}else{var e=a.Z(b);if(e&&this.ca(e,c.dm[d]))return s}return u},X:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.ca(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[\/\?#].*/,"");return a},ra:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.xa(document.location.href,d))return d.replace(/^[^\/]+(\/.*)/,"$1")+
"/"}return"/"},Wa:function(){if(!document.referrer)return k.p-k.z>c.vdur?1:4;var b=u;this.M(document.referrer)&&this.M(document.location.href)?b=s:(b=a.Z(document.referrer),b=this.ca(b||"",document.location.hostname));return b?k.p-k.z>c.vdur?1:4:3},getData:function(a){try{return l.get(a)||e.get(a)||m.get(a)}catch(b){}},setData:function(a,b,d){try{l.set(a,b,{domain:this.X(),path:this.ra(),W:d}),d?m.set(a,b,d):e.set(a,b)}catch(f){}},jb:function(a){try{l.set(a,"",{domain:this.X(),path:this.ra(),W:-1}),
e.remove(a),m.remove(a)}catch(b){}},pb:function(){var a,b,d,e,f;k.z=this.getData("Hm_lpvt_"+c.id)||0;13===k.z.length&&(k.z=Math.round(k.z/1E3));b=this.Wa();a=4!==b?1:0;if(d=this.getData("Hm_lvt_"+c.id)){e=d.split(",");for(f=e.length-1;0<=f;f--)13===e[f].length&&(e[f]=""+Math.round(e[f]/1E3));for(;2592E3<k.p-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(k.p);4<e.length;)e.shift();d=e.join(",");e=e[e.length-1]}else d=k.p,e="",f=1;this.setData("Hm_lvt_"+c.id,d,c.age);this.setData("Hm_lpvt_"+c.id,
k.p);d=k.p===this.getData("Hm_lpvt_"+c.id)?"1":"0";if(0===c.nv&&this.M(document.location.href)&&(""===document.referrer||this.M(document.referrer)))a=0,b=4;this.a.nv=a;this.a.st=b;this.a.cc=d;this.a.lt=e;this.a.lv=f},ob:function(){for(var a=[],b=this.a.et,d=+new Date,e=0,f=k.Ba.length;e<f;e++){var g=k.Ba[e],l=this.a[g];"undefined"!==typeof l&&""!==l&&("tt"!==g||"tt"===g&&0===b)&&(("ct"!==g||"ct"===g&&0===b)&&("kb"!==g||"kb"===g&&3===b))&&a.push(g+"="+encodeURIComponent(l))}switch(b){case 0:a.push("sn="+
k.A);this.a.rt&&a.push("rt="+encodeURIComponent(this.a.rt));break;case 3:a.push("sn="+k.A);break;case 5:a.push("sn="+k.A);a.push("_lpt="+this.w);a.push("_ct="+d);break;case 6:a.push("sn="+k.A);a.push("_lpt="+this.w);a.push("_ct="+d);break;case 85:a.push("sn="+k.A);break;case 90:this.a.rt&&a.push("rt="+this.a.rt)}return a.join("&")},qb:function(){this.pb();this.a.si=c.id;this.a.hca="0"===c.hca?r:c.hca;this.a.su=document.referrer;this.a.hh=window.location.hash;this.a.ds=p.lb;this.a.cl=p.colorDepth+
"-bit";this.a.ln=String(p.language).toLowerCase();this.a.ja=p.javaEnabled?1:0;this.a.ck=p.cookieEnabled?1:0;this.a.lo="number"===typeof _bdhm_top?1:0;this.a.fl=f.Ya();this.a.v="1.2.39";this.a.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");this.a.tt=document.title||"";this.a.vl=p.L()+p.B();var b=document.location.href;this.a.cm=a.k(b,k.bb)||"";this.a.cp=a.k(b,k.cb)||a.k(b,k.wb)||"";this.a.cw=a.k(b,k.ab)||a.k(b,k.yb)||"";this.a.ci=a.k(b,k.Za)||a.k(b,k.vb)||"";this.a.cf=a.k(b,k.eb)||a.k(b,k.xb)||
"";this.a.cu=a.k(b,k.$a)||a.k(b,k.ub)||""},init:function(){try{this.qb(),0===this.a.nv?this.nb():this.ga(".*"),h.b=this,this.Ia(),w.J("pv-b"),this.mb()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));d.log(k.da+"//"+k.ya+"?"+b.join("&"))}},mb:function(){function a(){w.J("pv-d")}this.sa?(this.aa=s,this.a.et=0,this.a.ep="",this.a.vl=p.L()+p.B(),this.i(a)):a();this.w=+new Date},
i:function(a){if(this.ta){var b=this;b.a.rnd=Math.round(Math.random()*k.G);w.J("stag-b");var e=k.da+"//"+k.ya+"?"+b.ob();w.J("stag-d");b.Ea(e);d.log(e,function(d){b.ga(d);g.d(a,"Function")&&a.call(b)})}},Ia:function(){var b=document.location.hash.substring(1),d=RegExp(c.id),e=a.Z(document.referrer)===k.Fa?1:0,f=a.k(b,"jn"),g=/^heatlink$|^select$|^pageclick$/.test(f);b&&(d.test(b)&&e&&g)&&(this.a.rnd=Math.round(Math.random()*k.G),b=document.createElement("script"),b.setAttribute("type","text/javascript"),
b.setAttribute("charset","utf-8"),b.setAttribute("src",k.protocol+"//"+c.js+f+".js?"+this.a.rnd),f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(b,f))},Ea:function(a){var b=e.get("Hm_unsent_"+c.id)||"",d=this.a.u?"":"&u="+encodeURIComponent(document.location.href),b=encodeURIComponent(a.replace(/^https?:\/\//,"")+d)+(b?","+b:"");e.set("Hm_unsent_"+c.id,b)},ga:function(a){var b=e.get("Hm_unsent_"+c.id)||"";b&&(a=encodeURIComponent(a.replace(/^https?:\/\//,"")),a=RegExp(a.replace(/([\*\(\)])/g,
"\\$1")+"(%26u%3D[^,]*)?,?","g"),(b=b.replace(a,"").replace(/,$/,""))?e.set("Hm_unsent_"+c.id,b):e.remove("Hm_unsent_"+c.id))},nb:function(){var a=this,b=e.get("Hm_unsent_"+c.id);if(b)for(var b=b.split(","),f=function(b){d.log(k.da+"//"+decodeURIComponent(b),function(b){a.ga(b)})},g=0,l=b.length;g<l;g++)f(b[g])}};return new b})();
(function(){var b=mt.event,a=mt.lang,d=h.l;if(c.kbtrk&&"undefined"!==typeof h.b){h.b.a.kb=a.va(h.b.a.kb)?h.b.a.kb:0;var f=function(){h.b.a.et=85;h.b.a.ep=h.b.a.kb;h.b.i()};b.c(document,"keyup",function(){h.b.a.kb++});b.c(window,"unload",function(){f()});setInterval(f,d.ib)}})();var B=h.l,C=h.load;c.pt&&C([B.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));
(function(){var b=mt.g,a=mt.lang,d=mt.event,f=mt.o;if("undefined"!==typeof h.b&&(c.med||(!b.ua||7<b.gb)&&c.cvcc)){var g,l,p,m,e=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},k=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===u)return u},w=function(b,d){var e={};e.n=g;e.t="clk";e.v=b;if(d){var k=d.getAttribute("href"),l=d.getAttribute("onclick")?""+d.getAttribute("onclick"):t,m=d.getAttribute("id")||"";p.test(k)?(e.sn="mediate",
e.snv=k):a.d(l,"String")&&p.test(l)&&(e.sn="wrap",e.snv=l);e.id=m}h.b.a.et=86;h.b.a.ep=f.stringify(e);h.b.i();for(e=+new Date;400>=+new Date-e;);};if(c.med)l="/zoosnet",g="swt",p=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,m={click:function(){for(var a=[],b=e(document.getElementsByTagName("a")),b=[].concat.apply(b,e(document.getElementsByTagName("area"))),b=[].concat.apply(b,e(document.getElementsByTagName("img"))),d,f,g=0,k=b.length;g<k;g++)d=b[g],f=d.getAttribute("onclick"),
d=d.getAttribute("href"),(p.test(f)||p.test(d))&&a.push(b[g]);return a}};else if(c.cvcc){l="/other-comm";g="other";p=c.cvcc.q||r;var n=c.cvcc.id||r;m={click:function(){for(var a=[],b=e(document.getElementsByTagName("a")),b=[].concat.apply(b,e(document.getElementsByTagName("area"))),b=[].concat.apply(b,e(document.getElementsByTagName("img"))),d,f,g,k=0,l=b.length;k<l;k++)d=b[k],p!==r?(f=d.getAttribute("onclick"),g=d.getAttribute("href"),n?(d=d.getAttribute("id"),(p.test(f)||p.test(g)||n.test(d))&&
a.push(b[k])):(p.test(f)||p.test(g))&&a.push(b[k])):n!==r&&(d=d.getAttribute("id"),n.test(d)&&a.push(b[k]));return a}}}if("undefined"!==typeof m&&"undefined"!==typeof p){var q;l+=/\/$/.test(l)?"":"/";var x=function(b,d){if(q===d)return w(l+b,d),u;if(a.d(d,"Array")||a.d(d,"NodeList"))for(var e=0,f=d.length;e<f;e++)if(q===d[e])return w(l+b+"/"+(e+1),d[e]),u};d.c(document,"mousedown",function(b){b=b||window.event;q=b.target||b.srcElement;var d={};for(k(m,function(b,e){d[b]=a.d(e,"Function")?e():document.getElementById(e)});q&&
q!==document&&k(d,x)!==u;)q=q.parentNode})}}})();(function(){var b=mt.e,a=mt.lang,d=mt.event,f=mt.o;if("undefined"!==typeof h.b&&a.d(c.cvcf,"Array")&&0<c.cvcf.length){var g={Ca:function(){for(var a=c.cvcf.length,f,m=0;m<a;m++)(f=b.qa(decodeURIComponent(c.cvcf[m])))&&d.c(f,"click",g.Ma())},Ma:function(){return function(){h.b.a.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.b.a.ep=f.stringify(a);h.b.i()}}};b.za(function(){g.Ca()})}})();
(function(){var b=mt.event,a=mt.o;if(c.med&&"undefined"!==typeof h.b){var d=+new Date,f={n:"anti",sb:0,kb:0,clk:0},g=function(){h.b.a.et=86;h.b.a.ep=a.stringify(f);h.b.i()};b.c(document,"click",function(){f.clk++});b.c(document,"keyup",function(){f.kb=1});b.c(window,"scroll",function(){f.sb++});b.c(window,"unload",function(){f.t=+new Date-d;g()});b.c(window,"load",function(){setTimeout(g,5E3)})}})();})();
